# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritefood',
            old_name='date',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='foodentry',
            old_name='date',
            new_name='entry_create_date',
        ),
    ]
