# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='auth_secret',
        ),
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
