# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 03:02
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20180506_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_date',
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
