# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_profile_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
